# Generated by Django 3.2 on 2024-01-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CinemaRate',
            new_name='MovieRate',
        ),
    ]
