# Generated by Django 3.2 on 2024-01-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_rename_cinemarate_movierate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.TextField(max_length=256, verbose_name='Название фильма'),
        ),
    ]
