# Generated by Django 3.2 on 2024-01-29 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poster', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_rate', to='users.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
