# Generated by Django 3.2 on 2024-02-05 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poster', '0006_movierate_unique_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='poster.movie', verbose_name='фильм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Избранный фильм',
                'verbose_name_plural': 'Избранные фильмы',
            },
        ),
        migrations.AddConstraint(
            model_name='favoritemovie',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='unique_favorite_movie'),
        ),
    ]
