# Generated by Django 3.2 on 2024-02-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0008_auto_20240211_1416'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movierate',
            name='unique_movie_rating',
        ),
        migrations.AddConstraint(
            model_name='movierate',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='unique_movie_rating'),
        ),
    ]
